# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shodantry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://shodan.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_23c0c8e400574510a163e2b95cb1f5f2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ce61489e355a4816ae18e74b14a618be }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: shodan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_23c0c8e400574510a163e2b95cb1f5f2 }}/shodan.azurecr.io/shodan:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shodantry'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_df724d468eb04450ab1954f3fa0e6c57 }}
        images: 'shodan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_23c0c8e400574510a163e2b95cb1f5f2 }}/shodan.azurecr.io/shodan:${{ github.sha }}'