name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/app1:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/app1:${{ github.sha }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shodanscanning'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/app1:${{ github.sha }}'
        multi-container-config-type: 'compose'
        multi-container-config-file: 'docker-compose.yml'
