# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shodantry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://shodan.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1cd0f9c207a942a9858e9845ae36bd60 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_092b8c26753a4be5b287f24aaaa7c288 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: shodan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1cd0f9c207a942a9858e9845ae36bd60 }}/shodantry_login:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shodantry'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f9b94bf7d92d4713ad0b94c6511827cf }}
        images: 'shodan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1cd0f9c207a942a9858e9845ae36bd60 }}/shodantry_login:${{ github.sha }}'